apiVersion: v1
kind: Service
metadata:
  name: fastapi-fibonacci-service
spec:
  selector:
    app: fastapi-fibonacci
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8000
      nodePort: 30081  # Для доступа извне на Windows
